# Generated by Django 3.1.6 on 2021-02-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUsers',
        ),
    ]
