# Generated by Django 3.1.6 on 2021-02-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_containers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='username',
        ),
        migrations.AddField(
            model_name='containers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
