# Generated by Django 3.1.6 on 2021-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='status',
        ),
        migrations.AddField(
            model_name='transfer',
            name='average_speed',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bytes_transferred',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='transfer',
            name='eta',
            field=models.CharField(default='~', max_length=1000),
        ),
        migrations.AddField(
            model_name='transfer',
            name='file_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='transfer',
            name='file_size',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='transfer',
            name='percentage',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='transfer',
            name='speed',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
