# Generated by Django 3.1.6 on 2021-04-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210407_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='file_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
