# Generated by Django 3.1.6 on 2021-04-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_command_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='stopped',
            field=models.BooleanField(default=False),
        ),
    ]
